version: '3'

services:
 app:
  build: ./meteoData
  ports:
   - "3000:3000"
  restart: always
  links:
   - mongo
   - api

 api:
  build: ./django_rest
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
   - ./django_rest:/code
  ports:
   - "8000:8000"

 mongo:
  image: mongo
  ports:
   - "27017:27017"